### ISSUE TITLE
Is there a way to use the arm-vita-eabi-gcc compiler with arm64 (M1 mac)?

### ISSUE THREAD

**Issue by spoiledbeef** [vitasdk/vdpm#79]
When trying to compile the HelloWorld sample, I get the following message:

The C compiler
"/Users/myuser/vitasdk/bin/arm-vita-eabi-gcc"
  is not able to compile a simple test program.

...

Reason: tried: '/usr/local/opt/zstd/lib/libzstd.1.dylib' (no such file), '/usr/local/lib/libzstd.1.dylib' **(mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')**), '/usr/lib/libzstd.1.dylib' (no such file)

Is it even possible to use the compiler with arm64?

**Comment by yellowbigbird83** [comment]
Hi, @jpssoares encounter the same issue. 
mac m1 pro, monterey v12.5
Any solutions please ?

**Comment by TresPorCiento** [comment]
I was able to build vdpm but...all the files are intel architecture. Useless inside an Apple Silicon device. The reason seems to be this team downloads some files that are just ready for intel. So this package does not consider an M1 processor. I tried to build vita-toolchain but is so horrible packaged that still not possible.
